### ISSUE TITLE
Moving large media files to G-Drive

### ISSUE THREAD

**Issue by jacksongoode** [MCT-master/mct-master.github.io#10]
See #7 for prior discussion.

Our plan is to move large media files (video, audio, images) from the repository to the shared G-Drive. Each student is responsible migrating their own media. See [here](https://github.com/MCT-master/mct-master.github.io/blob/master/README.md#embedding-images-videos-and-other-files) for instructions. This will also include renaming according to a new schema, see #11.

**Comment by stefanofasciani** [comment]
all files has been moved, and image resized.
