### ISSUE TITLE
Reducing size of .git (version control)

### ISSUE THREAD

**Issue by jacksongoode** [MCT-master/mct-master.github.io#12]
I am not entirely sure how we go about doing this but from what @ulrikah mentioned [here](https://github.com/MCT-master/mct-master.github.io/issues/7#issuecomment-575125117) this is quite an issue. Reducing it's size would be nice.

The only concern I have is that when we do reduce its size, we will also prevent reverting back to past commits.

**Comment by stefanofasciani** [comment]
there are several (recent) tutorials on how to do this

https://medium.com/@sangeethkumar.tvm.kpm/cleaning-up-a-git-repo-for-reducing-the-repository-size-d11fa496ba48 

https://docs.gitlab.com/ee/user/project/repository/reducing_the_repo_size_using_git.html

I believe it's better to do this once the migration has completed.

**Comment by stefanofasciani** [comment]
Files larger than 500 kb has been removed from the repo history, and files larger than 300 kb has been either compressed or migrated to GDrive (significantly slowed in loading images). Now the size of the repo is less than 300 MB (including current files and history).
It is recommended to trash the local copy of the repo, and clone it again.
