### ISSUE TITLE
Blog post title colors do not match

### ISSUE THREAD

**Issue by aleksati** [MCT-master/mct-master.github.io#16]
Not sure if this is an issue only on Chrome or on Windows, but the post title color seems to change ever so slightly for each post (see images below):

<p align="left">
<img src="https://user-images.githubusercontent.com/54307488/87028432-e3fb0200-c1de-11ea-8bba-086e8b2c6e35.jpg" width=350 height=500>
<img src="https://user-images.githubusercontent.com/54307488/87029186-0e998a80-c1e0-11ea-930b-ce4a88708e1c.jpg" width=400 height=500>
</p>

This might just be some code-remnant from the past where changing the post tile color-gradient was necessary to distinguish between posts. However, now it doesn't look that good anymore.

**Comment by stefanofasciani** [comment]
This is a feature of the theme, and it was there also before with the green text. This is common in many websites. If you have already visited an URL, the text color of the link changes (that's why it gets slightly darker). Should we remove it?

**Comment by aleksati** [comment]
Ah, okay. Yes, I think it looks better without it.

**Comment by stefanofasciani** [comment]
fixed by adding this code in assets/main.scss (override default minima template style)

a {
  color: $brand-color;
  text-decoration: none;

  &:visited {
    color: darken($brand-color, 0%);
  }

  &:hover {
    color: darken($brand-color, 20%);
    text-decoration: none;
  }

  .social-media-list &:hover {
    text-decoration: none;

    .username {
      text-decoration: none;
    }
  }
}
