### ISSUE TITLE
Issue with video tag as method for embedded videos

### ISSUE THREAD

**Issue by jacksongoode** [MCT-master/mct-master.github.io#23]
Just came across this. It looks like the first video method for embedding videos as detailed [here](https://github.com/MCT-master/Guides/wiki/How-to-use-the-MCT-Blog-%E2%80%90-Embedding-and-Storage-of-Files) does not consistently work for some files.

Here is an example of the second method (with iframe) vs. the first, using the video tag where no video appears - only audio. Thus it might make sense to abandon this first method with the video tag?

![Screen Recording 2020-09-25 at 21 14 24](https://user-images.githubusercontent.com/54308792/94307374-2f15ed00-ff64-11ea-9f4f-2acb8dcfc51a.gif)

**Comment by stefanofasciani** [comment]
That was a codec problem. In the code you tell the browser that the video is an MP4, but the video was encoded in a slightly different way. I took your .webm video from the G Drive, converted to MP4 using this https://cloudconvert.com/webm-to-mp4 and re-uploaded to G Drive (replaced the previous .mp4 file). Now it show on my browser and I haven't changed anything in the code of your post.

**Comment by stefanofasciani** [comment]
I have also added some details about this in the guide.
