### ISSUE TITLE
Merging "About" and "People"

### ISSUE THREAD

**Issue by ulrikah** [MCT-master/mct-master.github.io#25]
In my opinion, it makes sense to merge "About" and "People" on the webpage. To me, these two pages serve the same purpose as they exist now, i.e. presenting the MCT students to the outside the readers of the blog.

With the new "author's page" feature that was added over the summer, every student has the possibility of creating a presentation of themselves, which in some way renders the group presentations in "People" a bit obsolete. 

What do you think @stefanofasciani @AleksanderTidemann ?

**Comment by jacksongoode** [comment]
I agree with this. I also think the "About" page might make more sense to provide some information on the MCT programme itself.

Maybe it would be possible to add the list of students as a drop down that can be expanded for multiple classes, so it doesn't take up so much space.

**Comment by aleksati** [comment]
Hey,
I agree. This has been some source of confusion for me as well.  So there are two options I see as of now:

1. Re-structure an "About" page to include the posts from the first week of the groups AND a list of all the people. So on the same page. 

2. "About" is a dropdown menu, one item saying "about" and another saying "people", and under "people" is another list with "2019" "2020" and then a list with all student names.. or something like this.

3. Simply change "people" to the author's pages, and remove the first year posts. 

A combination of all 3 would probably be good. The second idea sounds a little too nested for my taste. Dropdown menus can be a real hassle for when using the blog on your cell-phone, for instance. Especially if there's going to be almost 20 items in it. But that's just my opinion. These long dropdown lists do work nicely in the Topics section, soo. Either way, **I'm game**. I think the best approach would be to create a new _layout HTML file for this page. That way it's easier to customize while not risking to damage other stuff. And also, add a small comment/title over the things you add to the CSS file.

I'm happy to help in any way I can. Do you, @ulrikah and @jacksonmgoode, want to try something out here together? If you build some prototypes locally using ruby, and take some pictures/screen captures, that would maybe be a good way of working I think.

**Comment by stefanofasciani** [comment]
When thinking about different solutions (dropdown, expanding) we have to think that right now in the About page we have only 3 intakes, but this will keep growing year by year.

I agree that details of student intakes should be moved from About to People, and that the About page should include information about the programme (perhaps just links to the UiO/NTNU website).

Perhaps in the section PEOPLE we can add at the top (header section where we have the text "The blog posts of this section present the various author of this ...") some expanding block or some other kind of structure to list students from the different intakes (with link o their author page).

I wont attempt the path with dropdown lists in the menu.

Give it a try and see if you can get anything that looks good. Once you are done we can see how it looks and push the changes in the repository (work on a branch at the moment). Thereafter, I can take care to add more contents in the About page.

**Comment by aleksati** [comment]
yeah, creating a seperate branch would probably be the best way of working on this.

**Comment by jacksongoode** [comment]
Oops - well, just see if the changes I made make sense! We can always revert, didn't see the separate branch comment :)

More resources/description should probably be added to the About page, but I think the People page is condensed nicely, and serves more of a singular purpose now.

**Comment by ulrikah** [comment]
I think it looks good! Very much what in line with what I thought when I opened the issue.

**Comment by stefanofasciani** [comment]
That looks good, well done. I will tweak it a little but next summer when I do annual round of polishing and maintenance.
