### ISSUE TITLE
Migrate to Jekyll 4?

### ISSUE THREAD

**Issue by jacksongoode** [MCT-master/mct-master.github.io#26]
Not sure how easy this would be - but there is a significant improvement in building the site locally (10x faster) which makes testing new posts an absolute breeze. This along with [other improvements](https://jekyllrb.com/news/2019/08/20/jekyll-4-0-0-released/) the Jekyll team has made.

Maybe just testing this out as a separate branch would be the proper thing to do?

**Comment by stefanofasciani** [comment]
we need to wait for Github Pages to update their backend https://pages.github.com/versions/
