### ISSUE TITLE
Make the blog UI compatible for mobile and tablet devices

### ISSUE THREAD

**Issue by aleksati** [MCT-master/mct-master.github.io#31]
Updating the CSS to make the navigation bar (among other things also) change when the blog is opened in a mobile or tablet environment. There might be various things that need to be done, but what I can think of now is:
* Make the dropdown menu appear on click. 
* experiment with UI design for Navigation bar on smaller screen sizes. 

Using the:
```
@media screen and (max-width: something something)
```
we can change the UI design when the browser page is below or over a certain threshold.

**Comment by aleksati** [comment]
An update on this issue. The navbar seems to work fine on mobile devices, meaning you can click “topics” and “projects” and the drop menu appears.

Only issue is that it looks weird. So it we should still add more formatting to accommodate mobile and touch devices.

**Comment by stefanofasciani** [comment]
The current version is definitely usable. Perhaps a more tight layout may look better (although it may be harder to use).
