### ISSUE TITLE
Make Wavesurfer audio widget avaliable globally 

### ISSUE THREAD

**Issue by aleksati** [MCT-master/mct-master.github.io#38]
Talking about the audio widget/audio visualization that appears in these posts, that Ulrik originally made: 
* https://mct-master.github.io/masters-thesis/2021/05/15/ulrikah-rave.html 
* https://mct-master.github.io/portal/2022/04/11/aleksati-5g-nmp.html 

Should be implemented so that you can just do this in a blog post to make it work: 
```
<div class="waveform" path="path-to-audio-file" color="optional-color-specification"/>
```

**Comment by stefanofasciani** [comment]
An option would be:
a) the <script> part will go into a .js file in utils (except the const myAudio = [] where you specify the filenames
b) the <style> part will go in main.scss (and hopefully this wont clash with other elements that are already in the blog style)
c) in the post you simply specify import the .js file from utils and specify the const myAudio[] array.
<script src="utils/waveplayer.js"></script>

**Comment by aleksati** [comment]
This feature should work now with any post.
