### ISSUE TITLE
G-Drive for many media items are not accessible

### ISSUE THREAD

**Issue by jacksongoode** [MCT-master/mct-master.github.io#43]
It looks like a lot of media items were moved away from G-Drive to another UiO hosted solution. I was actually wondering where these files were since I host some of the media on my own blog and it would be good to download them just in case :)

**Comment by stefanofasciani** [comment]
https://www.uio.no/english/studies/programmes/mct-master/blog/assets/

**Comment by jacksongoode** [comment]
Ah, ok I just found the commit with the redirects to this domain that were made. Thank you!
