### ISSUE TITLE
Compiling/deployment time

### ISSUE THREAD

**Issue by Eigil94** [MCT-master/mct-master.github.io#6]
Updates seem to take an extraordinary long time to manifest on the website. Anyone know what's causing it/what can be done?

**Comment by ulrikah** [comment]
Is this still an issue, or should we close it? @Eigil94

**Comment by stefanofasciani** [comment]
Once you commit a change the files appears on the online repo almost immediately, but for the blog, you need to wait until jekyll (on the github server, not on your local machine) re-generate the static blog site. There is no way to speed up this process (jekyll runs on github servers and we have no access to it). However, if the local preview looks (your local jekyll) looks fine, it will be fine also when manifested online.
