### ISSUE TITLE
Organizing assests

### ISSUE THREAD

**Issue by jacksongoode** [MCT-master/mct-master.github.io#8]
This one is going to be tough because it would mean updating all the references in the blog posts. I've been looking for a plugin or some app that integrates into VS and has this functionality. I feel like it exists. Let me know if anyone finds one.

**Comment by ulrikah** [comment]
What sort of folder structure are you thinking of for organizing them into? Is it sufficient with `assets/video`, `assets/img`, `assets/sounds` and `assets/code`, or are you thinking of something more detailed?

**Comment by jacksongoode** [comment]
Now that we have a labeling schema (see [this change](https://github.com/MCT-master/mct-master.github.io/commit/fe0f54dd3b001f53adefce302b6e865f5916e33b) to the guide), I think it is less of an issue and something we can resolve once media renaming is complete.

**Comment by stefanofasciani** [comment]
reorganization complete. An updated description on how to use the blog is available here https://github.com/MCT-master/Guides/wiki
